### ISSUE TITLE
Output is looks to hard to read

### ISSUE THREAD

**Issue by KamilUtkuMeliora** [kamilutkumavi0/lh#1]
Need to be table like for easy to read

**Comment by kamilutkumavi0** [comment]
![image](https://github.com/kamilutkumavi0/lh/assets/114648102/e31b3bd6-9733-40fc-be7a-ed12869b0ac6)
Tabular print is available now

**Comment by kamilutkumavi0** [comment]
Bugs are solved ready for documentation, READ.me and wiki page
