### ISSUE TITLE
Panic on windows

### ISSUE THREAD

**Issue by KamilUtkuMeliora** [kamilutkumavi0/lh#10]
thread 'main' panicked at ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lh-0.1.2\src\output_printer.rs:23:67:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```rust
let element = OutputElement::new(element_text, i.file_type.unwrap().color);
```

**Comment by kamilutkumavi0** [comment]
Now its going to give error in that spasific file why it can't readable than I will try to fix it too
